### ISSUE TITLE
create new grant

### ISSUE THREAD

**Issue by rrd108** [rrd108/grants#16]
1. have a link in the top menu "New Grant" (/grants/add)
2. In the /grants/add view put a link to the issuer where new issuer can be added
3. after the grant is added if a company is selected redirect to companies-grants/view/idOfTheNewlyCreatedCompaniesGrants
4. automatically add a new history event with status id 11 (created)

**Comment by ifjuszalaimihaly** [comment]
There is an multiple select for companies in the grants/add.ctp. Is it direct, or have to change to simple select?

**Comment by rrd108** [comment]
Ha jól látom itt hiányzik a 2-es pont az add issuer link

**Comment by ifjuszalaimihaly** [comment]
![image](https://user-images.githubusercontent.com/28926078/33238318-c7939130-d28b-11e7-8203-76066965d5b0.png)
Ott van az a link is

**Comment by rrd108** [comment]
ehh, nem kommunikáltam egyértelműen. Azt szeretném ha a link az issuer select mellett lenne közvetlenül Azaz ha a user elkezd felvinni egy új pályázatot és nincs a kibocsájtó a listában akkor kiüsse a szemét a link.
